### ISSUE TITLE
Not clear that filtering requires embedded double quotes (in some cases maybe)

### ISSUE THREAD

**Issue by ijabz** [japlscript/japlscript#2]
I had this code
```

protected FileTrack findExistingTrackInLibrary(String persistentId)
    {
        //Find existing track in MusicApp global playlist
        Application app = Application.getInstance();
        Playlist globalPlaylist = app.getPlaylist(0);
        Track[] tracks = globalPlaylist.getTracks("persistent ID = " + persistentId);
        if(tracks!=null && tracks.length>0)
        if(tracks[0].isInstanceOf(FileTrack.CLASS))
        {
            return tracks[0].cast(FileTrack.class);
        }
        return null;
    }
```

to find track in global playlist and it failed giving

 NSAppleScriptErrorBriefMessage = "The variable FCFAA55D74755830 is not defined."; NSAppleScriptErrorMessage = "The variable FCFAA55D74755830 is not defined."; NSAppleScriptErrorNumber = "-2753"; NSAppleScriptErrorRange = "NSRange: {76, 16}"; }

I need to put persistentId in double quotes
```

  protected FileTrack findExistingTrackInLibrary(String persistentId)
    {
        //Find existing track in MusicApp global playlist
        Application app = Application.getInstance();
        Playlist globalPlaylist = app.getPlaylist(0);
        Track[] tracks = globalPlaylist.getTracks("persistent ID = "+"\"" + persistentId + "\"");
        if(tracks!=null && tracks.length>0)
        if(tracks[0].isInstanceOf(FileTrack.CLASS))
        {
            return tracks[0].cast(FileTrack.class);
        }
        return null;
    }

```
for it to work

Not very clear this is required, unclear if  it is always required because your exmple in the README.md doesnt show double quotes

int count = playlist.countTracks("year > 1984");

**Comment by hendriks73** [comment]
You have to use the correct AppleScript datatype. What's passed as qualifier (`getTracks(qualifier);`) is passed verbatim to AppleScript, so it has to conform to AppleScript rules. In AppleScript, strings have to be quoted. Integer literals (like in the example), don't have to be quoted.

Fixed in https://github.com/japlscript/japlscript/commit/1195e8099cd6cad5f55e66d5f6b5653cd93d9524

**Comment by ijabz** [comment]
Thanks for updating the documentation. The real strength of this lib is to allow developers to write code without having to know applescript that well, so it is helpful for this kind of things to be in the docs.

**Comment by hendriks73** [comment]
Agreed. Thanks for making me aware of it.
