### ISSUE TITLE
The link in README.md for the api docs for most subprojects fails

### ISSUE THREAD

**Issue by ijabz** [japlscript/japlscript#4]
Hi, the link in README.md for the api docs for most subprojects fails

e.g 
https://hendriks73.github.io/obstspot/com/tagtraum/macos/spotify/package-summary.html

Only works for japlscript, obtunes and obtsmusic

**Comment by hendriks73** [comment]
It's fixed (and has been fixed for a while) in the dev branch. But since that is the only change (if I remember correctly), it hasn't been pushed to main yet.

**Comment by hendriks73** [comment]
Dev has been released.
