### ISSUE TITLE
My application is failing notarisation because japlscript-x86_64-3.4.10.dylib and japlscript-aarch 64-3.4.10.dylib are not signed

### ISSUE THREAD

**Issue by ijabz** [japlscript/japlscript#5]
My application is failing notarisation because "songkong-osx.dmg/SongKong.app/Contents/Java/japlscript-executor-3.4.10.jar/japlscript-x86_64-3.4.10.dylib. is not signed

https://osxapps-ssl.itunes.apple.com/itunes-assets/Enigma126/v4/95/5a/b8/955ab8eb-8f41-d019-fec9-56c3aaeac4c9/developer_log.json?accessKey=1650058449_7191395120682680054_9LKYDkRvAQFBIYw6jgN%2F49ZiWIaNusPNbBtvF6o10pZ6YKUIynsaS%2BaUXE1qy4kwOCmU2X10173saaccZ%2BPctMi8oGhiLO1VunVHQ%2Fxj83TyysEy31ZEkV9EkVNWiKFxMsqzFJCHmjVAKzzuznAGh4DaENeG6etPBDWoIz17u3o%3D

Can it be provided signed or do I have to sign this myself, I do have the credentials and build system to notarise my own application but I don't know how this fits in with signing the third party dynamic lib

This is the signing part of my build
```
export CODESIGN_ALLOCATE="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate"
/usr/bin/codesign --timestamp --options runtime \
--entitlements $HOME/code/jthink/songkong/songkong.entitlements \
--sign "Developer ID Application: P Taylor" \
--force --deep --verbose /Applications/SongKong.app
/usr/bin/codesign -vvv --deep --strict /Applications/SongKong.app
spctl -a -t exec -vv /Applications/SongKong.app
cd $HOME/code/jthink/SongKong
/usr/local/bin/dmgcanvas $HOME/code/jthink/SongKong/dmgCanvas_songkong.dmgCanvas $HOME/songkong-osx.dmg -v SongKong -identity "Developer ID Application: P Taylor" -notarizationAppleID paultaylor@jthink.net -notarizationPassword xxxxxxxxxxxxxxxxxxx -notarizationPrimaryBundleID songkong
```

Also note I rebuilt obsmusic and obstuynes locally to resolve the issue with addNewTracks not returning an array, but I didn't rebuild japlscript so I don't think this I cause of issue

       <dependency>
            <groupId>com.tagtraum</groupId>
            <artifactId>obstmusic</artifactId>
            <version>0.9.6</version>
        </dependency>
        <dependency>
            <groupId>com.tagtraum</groupId>
            <artifactId>obstunes</artifactId>
            <version>0.9.6</version>
        </dependency>

**Comment by hendriks73** [comment]
You need to sign it yourself.

**Comment by ijabz** [comment]
Oh, do you know what I have to add my builld to do this, I dont understand these commands just copied from someone else.

**Comment by ijabz** [comment]
Also I dont understand why I have to sign it, arent 3rd party libs usually provided already signed ?

**Comment by ijabz** [comment]
Im already signing **deep** so I dont see what else I can do

```
/usr/bin/codesign --timestamp --options runtime \
--entitlements $HOME/code/jthink/songkong/songkong.entitlements \
--sign "Developer ID Application: P Taylor" \
--force --deep --verbose /Applications/SongKong.app
```

**Comment by ijabz** [comment]
Maybe this is not a japlscript question although i think most Java developers would find it confusing they have to sigh a third party dependency so I have created

https://stackoverflow.com/questions/71860657/how-do-i-modify-my-java-appbundler-build-to-sign-3rd-party-library

**Comment by hendriks73** [comment]
To sign [casamplesp](https://www.tagtraum.com/casampledsp/) libraries, I do the following:

```bash
# sign dylibs in jars
unzip -j jar_dir/casampledsp-complete* '*.dylib'
codesign -vvv -f --sign "Developer ID Application: Whatever Your Name Is" *.dylib
jar -uvf jar_dir/casampledsp-complete*  casampledsp*
rm casampledsp*
```

I.e. I extract the `*.dylib` files, sign them, and stick them back in the using the jar flags `-uvf`.

To make this work for your app, just replace `jar_dir` with the directory name of your macOS app jars.

**Comment by hendriks73** [comment]
That said, I would love to JaplScript native libraries to already be signed, just never had the time to integrate that into the GitHub workflow in a secure way. There is also the issue of using some certificate that has to be paid for.

**Comment by ijabz** [comment]
Thanks, okay I get it to now, you cant sign files when within the jar, I added the following based on your example to get it working
```

unzip -j /Applications/SongKong.app/Contents/Java/japlscript-executor-3.4.10.jar -d /Applications/SongKong.app/Contents/Java/EXTRACT
export CODESIGN_ALLOCATE="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate"
/usr/bin/codesign --timestamp --options runtime \
--sign "Developer ID Application: P Taylor" \
--force --verbose /Applications/SongKong.app/Contents/Java/EXTRACT/*.dylib
cd /Applications/SongKong.app/Contents/Java/EXTRACT
jar -uvf /Applications/SongKong.app/Contents/Java/japlscript-executor-3.4.10.jar *.dylib
rm -fr /Applications/SongKong.app/Contents/Java/EXTRACT
cd $HOME/code/jthink/songkong

```
and this has worked and allowed notarization

I think you should add something to the README.md to japlscript as non obvious.

**Comment by hendriks73** [comment]
As a reminder to myself: [this website](https://localazy.com/blog/how-to-automatically-sign-macos-apps-using-github-actions) explains how to sign apps/libs with a GitHub workflow. The approach is very similar to JAR signing for Maven deployment.

**Comment by hendriks73** [comment]
The packaged dylibs are now (i.e. v3.4.11 or later) signed before they are being deployed to Maven central. You should not need to sign them yourself anymore.

Please re-open this issue, should you still have trouble with this.

**Comment by ijabz** [comment]
Thanks, would be good to release new versions of obtsmusic, obtstunes ecetera so that they use the signed version of japscript.

**Comment by hendriks73** [comment]
Done.
